#!/usr/bin/env ruby
require "artii"
require "colorize"
require "./controller/SuperheroesController"
require 'tty-prompt'   

puts "\e[H\e[2J"
puts ""
puts "welcome to the ".center(100)
a = Artii::Base.new
puts a.asciify("Superhero  Database").blue 

begin

    prompt = TTY::Prompt.new
    choices = [ 
        { name: "List all the superheroes", value: list },
        { name: "Create a new superhero", value: create },
        { name: "Search the superhero database", value: search },
        { name: "Edit a superhero", value: edit },
        { name: "Delete a superhero", value: delete },
        { name: "Help with the database", value: help },
        { name: "Exit the database", value: exit }
]

input = prompt.select("Main menu", choices)


case input
    when list
        SuperheroesController.index
    when create
        SuperheroesController.create
    when search
        
    when edit

    when delete
        SuperheroesController.destroy
    when help
end
end until input == exit

# superhero = Superhero.new "Batman"

# Superhero.new "Superman"
# Superhero.new "Spider-man"

# puts superhero
# puts "----"

# id = 4
# superhero1 = Superhero.find(id)

# puts "#{superhero1} hello"
# puts Superhero.all # List all the superheroes
