#!/usr/bin/env ruby

require "./controller/SuperheroesController"
require 'tty-prompt'   

    puts "Welcome to the superhero database"

begin
    prompt = TTY::Prompt.new
    choices = [ 
        { name: "List all the superheroes", value: 1 },
        { name: "Create a new superhero", value: 2 },
        { name: "Search the superhero database", value: 3 },
        { name: "Edit/delete a superhero", value: 4 },
        { name: "Help with the database", value: 5 },
        { name: "Exit the database", value: 6 }
]

input = prompt.select("Main menu", choices)


case input
    when 1
        SuperheroesController.index
    when 2
        SuperheroesController.create
    when 3
        
    when 4
        SuperheroesController.destroy
    when 5
end
end until input == 6

# superhero = Superhero.new "Batman"

# Superhero.new "Superman"
# Superhero.new "Spider-man"

# puts superhero
# puts "----"

# id = 4
# superhero1 = Superhero.find(id)

# puts "#{superhero1} hello"
# puts Superhero.all # List all the superheroes
